name: _
publish_to: none
description: Modular, fast, progressive database for Dart and Flutter.
homepage: https://github.com/dipdev-studio/dip_db
repository: https://github.com/dipdev-studio/dip_db

environment:
  sdk: ^3.6.0

dev_dependencies:
  melos: ^3.4.0

workspace:
  - packages/dip_db_core
  - packages/dip_db_dart
  - packages/dip_db_flutter
