name: dip_db_core
description: Modular, fast, progressive database for Dart and Flutter
version: 0.0.1-alpha
homepage: https://github.com/dipdev-studio/dip_db
repository: https://github.com/dipdev-studio/dip_db

environment:
  sdk: ^3.6.0
resolution: workspace

#dependencies:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
